



const SB_URL='https://gtizbvbufskdkemtuems.supabase.co';const SB_KEY='sb_publishable_TH4BwX7f0byE09zRWdtVtg_TyczbAP3';const sb=supabase.createClient(SB_URL,SB_KEY);let C=null;

// ── AUTH ──
let authMode='login';
function toggleAuthMode(){authMode=authMode==='login'?'register':'login';document.getElementById('auth-user').classList.toggle('hidden',authMode==='login');document.getElementById('auth-btn').textContent=authMode==='login'?'LOGIN':'REGISTER';document.getElementById('auth-toggle').textContent=authMode==='login'?'New? Register here':'Have account? Login';document.getElementById('auth-error').textContent='';}
async function doAuth(){
  const e=document.getElementById('auth-email').value.trim(),p=document.getElementById('auth-pass').value,u=document.getElementById('auth-user').value.trim();
  document.getElementById('auth-error').textContent='';
  if(!e||p.length<6){document.getElementById('auth-error').textContent='Email + password (6+ chars) required';return;}
  if(authMode==='login'){
    const{data,error}=await sb.auth.signInWithPassword({email:e,password:p});
    if(error){document.getElementById('auth-error').textContent=error.message;return;}
    C=data.user;document.getElementById('auth-overlay').style.display='none';updateDeskItems();toast('Welcome back!');
  }else{
    if(!u){document.getElementById('auth-error').textContent='Pick a username';return;}
    const{data,error}=await sb.auth.signUp({email:e,password:p,options:{data:{username:u}}});
    if(error){document.getElementById('auth-error').textContent=error.message;return;}
    if(data.user){C=data.user;document.getElementById('auth-overlay').style.display='none';updateDeskItems();toast('Welcome, @'+u+'!');}
    else{document.getElementById('auth-error').textContent='Check your email. Or disable email confirmation in Supabase > Settings.';}
  }
}
async function checkSession(){const{data:{session}}=await sb.auth.getSession();if(session){C=session.user;document.getElementById('auth-overlay').style.display='none';updateDeskItems();}else{document.getElementById('auth-overlay').style.display='flex';}}
setTimeout(checkSession,500);
setTimeout(checkSession,300);
function toast(m,d=2500){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',d);}
function initStars(){const c=document.getElementById('star-cnv'),ctx=c.getContext('2d');c.width=window.innerWidth;c.height=window.innerHeight;const s=[];for(let i=0;i<80;i++)s.push({x:Math.random()*c.width,y:Math.random()*c.height,r:.5+Math.random()*2,c:['#ff1493','#0ff','#cf0','#fff','#da70d6'][i%5],sp:.005+.01*Math.random(),a:Math.random()*Math.PI*2});function draw(){ctx.clearRect(0,0,c.width,c.height);s.forEach(p=>{p.a+=p.sp;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=p.c;ctx.globalAlpha=.3+.7*Math.abs(Math.sin(p.a));ctx.fill();});ctx.globalAlpha=1;requestAnimationFrame(draw);}draw();}
function initSparkles(){const cl=['#ff1493','#0ff','#cf0','#da70d6','#ffd700','#fff','#ff69b4','#40e0d0'];for(let i=0;i<35;i++){const d=document.createElement('div');d.className='sparkle';d.style.left=Math.random()*100+'%';d.style.top=Math.random()*100+'%';d.style.background=cl[i%8];d.style.setProperty('--d',(1.2+Math.random()*3)+'s');d.style.setProperty('--c',cl[i%8]);d.style.animationDelay=Math.random()*4+'s';document.body.appendChild(d);}}
function initTape(){for(let i=0;i<5;i++){const t=document.createElement('div');t.className='tape-strip';t.style.left=(5+Math.random()*85)+'%';t.style.top=(8+Math.random()*80)+'%';t.style.width=(40+Math.random()*80)+'px';t.style.setProperty('--r',((Math.random()*10)-5)+'deg');document.body.appendChild(t);}}
function updateClock(){document.getElementById('tb-clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}setInterval(updateClock,1000);updateClock();
function toggleStart(){document.getElementById('start-menu').classList.toggle('open');}document.addEventListener('click',e=>{if(!e.target.closest('#start-menu')&&!e.target.closest('.sb-start'))document.getElementById('start-menu').classList.remove('open');});
function toggleSky(){document.body.classList.toggle('sky');const m=document.getElementById('sb-theme'),b=document.getElementById('btn-sky');const sky=document.body.classList.contains('sky');if(m)m.textContent=sky?'☀️':'🌙';if(b){b.textContent=sky?'🌙 DARK':'☀️ LIGHT';b.classList.remove('gba','gbb','gbc','gbd');b.classList.add(sky?'gbd':'gbc');}toast(sky?'☀️ Light ON':'🌙 Dark ON');}
function navigateTo(vid){document.querySelectorAll('.view-panel').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.sb-btn').forEach(b=>b.classList.remove('active'));const v=document.getElementById(vid);if(v)v.classList.add('active');const b=document.querySelector('.sb-btn[data-view="'+vid+'"]');if(b)b.classList.add('active');setTimeout(updateDeskItems,100);}
document.addEventListener('DOMContentLoaded',()=>{initStars();initSparkles();initTape();document.querySelectorAll('.sb-btn[data-view]').forEach(b=>b.addEventListener('click',()=>navigateTo(b.dataset.view)));initAvatar();initHub();initFoodStars();initCalendar();initAlbum();initTama();initWinamp();initPeer();});
function openPopup(id){const p=document.getElementById(id);if(p){p.classList.add('open');p.style.zIndex=++pZ;}}function closePopup(id){document.getElementById(id)?.classList.remove('open');}
let pZ=720,drag=null,dOX=0,dOY=0;document.addEventListener('mousedown',e=>{const bar=e.target.closest('.w-title')||e.target.closest('.mac-titlebar');if(!bar)return;const pop=bar.closest('.w-popup');if(!pop)return;drag=pop;dOX=e.clientX-pop.offsetLeft;dOY=e.clientY-pop.offsetTop;pop.style.zIndex=++pZ;});document.addEventListener('mousemove',e=>{if(drag){drag.style.left=(e.clientX-dOX)+'px';drag.style.top=(e.clientY-dOY)+'px';}});document.addEventListener('mouseup',()=>{drag=null;});
const DOLL_BASES={f:'https://pixeldolls.net/dollmakers/files/bratz/br_base-10.gif',m:'https://pixeldolls.net/dollmakers/files/bratz/br_base-10.gif',x:'https://pixeldolls.net/dollmakers/files/bratz/br_base-12.gif'};
const AV={hair:[{id:'h1',n:'Blonde',u:'https://pixeldolls.net/dollmakers/files/bratz/hair42.gif',g:'u'},{id:'h2',n:'Brunette',u:'https://pixeldolls.net/dollmakers/files/bratz/hair25.gif',g:'u'},{id:'h3',n:'Pink',u:'https://pixeldolls.net/dollmakers/files/bratz/hair31.gif',g:'u'},{id:'h4',n:'Blue',u:'https://pixeldolls.net/dollmakers/files/bratz/hair5.gif',g:'u'},{id:'h5',n:'Black Long',u:'https://pixeldolls.net/dollmakers/files/bratz/hair1.gif',g:'u'},{id:'h6',n:'Red',u:'https://pixeldolls.net/dollmakers/files/bratz/hair10.gif',g:'u'},{id:'h7',n:'Short Blue',u:'https://pixeldolls.net/dollmakers/files/bratz/hair8.gif',g:'m'},{id:'h8',n:'Buns',u:'https://pixeldolls.net/dollmakers/files/bratz/hair19.gif',g:'f'},{id:'h9',n:'Green Pixie',u:'https://pixeldolls.net/dollmakers/files/bratz/hair44.gif',g:'x'},{id:'h10',n:'Spiky Black',u:'https://pixeldolls.net/dollmakers/files/bratz/hair11.gif',g:'m'}],top:[{id:'t1',n:'Pink Tank',u:'https://pixeldolls.net/dollmakers/files/bratz/top19.gif',g:'f'},{id:'t2',n:'Black Tee',u:'https://pixeldolls.net/dollmakers/files/bratz/top7.gif',g:'u'},{id:'t3',n:'Blue Top',u:'https://pixeldolls.net/dollmakers/files/bratz/top12.gif',g:'f'},{id:'t4',n:'White Shirt',u:'https://pixeldolls.net/dollmakers/files/bratz/top1.gif',g:'u'},{id:'t5',n:'Purple Blouse',u:'https://pixeldolls.net/dollmakers/files/bratz/top15.gif',g:'f'},{id:'t6',n:'Green Tee',u:'https://pixeldolls.net/dollmakers/files/bratz/top3.gif',g:'m'},{id:'t7',n:'Red Top',u:'https://pixeldolls.net/dollmakers/files/bratz/top9.gif',g:'f'},{id:'t8',n:'Grey Hoodie',u:'https://pixeldolls.net/dollmakers/files/bratz/top22.gif',g:'m'}],bottom:[{id:'b1',n:'Black Jeans',u:'https://pixeldolls.net/dollmakers/files/bratz/pants14.gif',g:'u'},{id:'b2',n:'Blue Jeans',u:'https://pixeldolls.net/dollmakers/files/bratz/pants9.gif',g:'u'},{id:'b3',n:'Pink Skirt',u:'https://pixeldolls.net/dollmakers/files/bratz/pants4.gif',g:'f'},{id:'b4',n:'White Pants',u:'https://pixeldolls.net/dollmakers/files/bratz/pants1.gif',g:'u'},{id:'b5',n:'Red Skirt',u:'https://pixeldolls.net/dollmakers/files/bratz/pants6.gif',g:'f'},{id:'b6',n:'Cargo Pants',u:'https://pixeldolls.net/dollmakers/files/bratz/pants11.gif',g:'m'}],shoes:[{id:'s1',n:'Platforms',u:'https://pixeldolls.net/dollmakers/files/bratz/shoe2.gif',g:'u'},{id:'s2',n:'Fur Boots',u:'https://pixeldolls.net/dollmakers/files/bratz/shoe3.gif',g:'f'},{id:'s3',n:'Heels',u:'https://pixeldolls.net/dollmakers/files/bratz/shoe5.gif',g:'f'},{id:'s4',n:'Sandals',u:'https://pixeldolls.net/dollmakers/files/bratz/shoe1.gif',g:'u'},{id:'s5',n:'Sneakers',u:'https://pixeldolls.net/dollmakers/files/bratz/shoe10.gif',g:'m'},{id:'s6',n:'Black Boots',u:'https://pixeldolls.net/dollmakers/files/bratz/shoe12.gif',g:'u'}]};
let avGender='f',avCat='hair',avIdx={hair:0,top:0,bottom:0,shoes:0};
function initAvatar(){document.querySelectorAll('.av-g-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.av-g-btn').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');avGender=b.dataset.g;document.getElementById('doll-base').src=DOLL_BASES[avGender];renderAvItems();}));renderAvCats();renderAvItems();updateDoll();}
function renderAvCats(){const el=document.getElementById('av-cats');if(!el)return;el.innerHTML=Object.keys(AV).map(k=>'<button class="av-cat'+(k===avCat?' sel':'')+'" onclick="setAvCat(\''+k+'\')">'+k.toUpperCase()+'</button>').join('');}
function setAvCat(c){avCat=c;renderAvCats();renderAvItems();}
function renderAvItems(){const el=document.getElementById('av-items');if(!el)return;const items=AV[avCat].filter(i=>i.g==='u'||i.g===avGender||avGender==='x');el.innerHTML=items.map((item,i)=>{const oi=AV[avCat].indexOf(item);return '<div class="av-item'+(avIdx[avCat]===oi?' sel':'')+'" onclick="pickAv(\''+avCat+'\','+oi+')"><img src="'+item.u+'" onerror="this.src=\'data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%2255%22 height=%2255%22><rect fill=%22%23ff1493%22 width=%2255%22 height=%2255%22/><text fill=%22white%22 x=%2227%22 y=%2232%22 text-anchor=%22middle%22 font-size=%229%22>'+item.n.substring(0,4)+'</text></svg>\'"><div class="av-item-name">'+item.n+'</div></div>';}).join('');}
function pickAv(cat,idx){avIdx[cat]=idx;renderAvItems();updateDoll();}
function updateDoll(){const h=AV.hair[avIdx.hair],t=AV.top[avIdx.top],b=AV.bottom[avIdx.bottom],s=AV.shoes[avIdx.shoes];const dh=document.getElementById('doll-hair'),dt=document.getElementById('doll-top'),db=document.getElementById('doll-pants'),ds=document.getElementById('doll-shoes');if(h){dh.src=h.u;dh.style.display='block';dh.style.width='260px';dh.style.left='0';dh.style.top='-10px';}if(t){dt.src=t.u;dt.style.display='block';dt.style.width='260px';dt.style.left='0';dt.style.top='0';}if(b){db.src=b.u;db.style.display='block';db.style.width='260px';db.style.left='0';db.style.top='0';}if(s){ds.src=s.u;ds.style.display='block';ds.style.width='260px';ds.style.left='0';ds.style.top='0';}}
function randomAvatar2(){Object.keys(avIdx).forEach(k=>avIdx[k]=Math.floor(Math.random()*AV[k].length));renderAvItems();updateDoll();}
function saveAvatar2(){toast('Avatar saved!');}

// ── PROFILE PHOTO ──
function uploadProfilePhoto(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{localStorage.setItem('wf_profile_photo',ev.target.result);updateDeskItems();toast('Profile photo updated!');};r.readAsDataURL(f);}
function pickGifAvatar(){
  const gifPool=[...FILM_GIFS,{src:'https://i.pinimg.com/originals/87/e2/e0/87e2e02f70cd4ed3f14d707fc1eb516b.gif',cap:'mood'},{src:'https://i.pinimg.com/originals/46/f1/ac/46f1ac827de4f7a9e5521a864321bb0b.gif',cap:'y2k'},{src:'https://i.pinimg.com/originals/84/9b/0d/849b0d3f428a3e726db7d6ce97d76afb.gif',cap:'girl'}];
  const html=gifPool.map((g,i)=>'<img src="'+g.src+'" style="width:45px;height:45px;object-fit:cover;cursor:pointer;border:2px solid transparent;border-radius:4px;margin:2px;" onclick="selectGifAvatar(\''+g.src+'\')" title="'+g.cap+'">').join('');
  const w=window.open('','_blank','width=400,height=300');w.document.write('<html><head><title>Pick GIF</title><style>body{background:#0a0a14;text-align:center;padding:10px;font-family:sans-serif;color:#ff1493;}</style></head><body><h3>Choose a GIF</h3>'+html+'<br><button onclick="window.close()" style="margin-top:8px;">Close</button><script>function selectGifAvatar(u){opener.localStorage.setItem(\"wf_profile_photo\",u);opener.updateDeskItems();window.close();}<\/script></body></html>');
}
function updateUsername(){const u=document.getElementById('av-username').value.trim();if(u){localStorage.setItem('wf_username',u);updateDeskItems();toast('Username updated!');}}function selectGifAvatar(u){localStorage.setItem('wf_profile_photo',u);updateDeskItems();toast('Photo updated!');}
function toggleSimsBubbles(e){e.stopPropagation();const el=document.getElementById('sims-bubbles');el.innerHTML='';const opts=['Pose...','Flirt','Call...','Dance!','Taunt','Sing','High Fashion'];opts.forEach((o,i)=>{const b=document.createElement('div');b.className='sims-bubble';b.textContent=o;b.style.position='absolute';b.style.left=(20+(i*55)%280)+'px';b.style.top=(130+(i%3)*40)+'px';b.onclick=ev=>{ev.stopPropagation();toast('✦ '+o+' ✦');el.innerHTML='';};el.appendChild(b);});setTimeout(()=>{el.innerHTML='';},4000);}
const hubCats=['Music','Podcasts','TV','Movies','Anime','Games'];const hubData={individual:{},group:{}};hubCats.forEach(c=>{hubData.individual[c]=[];hubData.group[c]=[];});let hubMode='individual';
function initHub(){renderHub();}function hubTab(m){hubMode=m;renderHub();}
function renderHub(){const g=document.getElementById('hub-grid');if(!g)return;g.innerHTML=hubCats.map(c=>{const items=hubData[hubMode][c]||[];return '<div class="myspace-panel"><h4>'+c+'</h4>'+items.map(i=>'<div style="font-size:10px;margin:2px 0;display:flex;align-items:center;gap:4px;"><span>'+i.icon+'</span>'+i.title+'</div>').join('')+'<div style="display:flex;gap:3px;margin-top:4px;"><input class="inp w95" placeholder="Add..." style="font-size:9px;flex:1;" id="hu-'+c+'"><input class="inp w95" placeholder="ico" style="width:35px;font-size:14px;text-align:center;" id="hu-ico-'+c+'" maxlength="2" value="⭐"><button class="btn w95" onclick="addHub(\''+c+'\')">+</button></div></div>';}).join('');}
function addHub(c){const i=document.getElementById('hu-'+c),ico=document.getElementById('hu-ico-'+c);if(!i||!i.value.trim())return;hubData[hubMode][c].push({title:i.value.trim(),icon:ico?.value||'⭐',author:C?.email||'anon'});i.value='';renderHub();}
let fRating=0,fReviews=[];
function initFoodStars(){const s=document.getElementById('food-stars');if(!s)return;s.innerHTML='';for(let i=1;i<=5;i++){const st=document.createElement('span');st.textContent='☆';st.style.cursor='pointer';st.addEventListener('click',()=>{fRating=i;updateFS();});st.addEventListener('mouseenter',()=>{s.querySelectorAll('span').forEach((x,j)=>x.textContent=j<i?'★':'☆');});st.addEventListener('mouseleave',updateFS);s.appendChild(st);}}
function updateFS(){const s=document.getElementById('food-stars');if(s)s.querySelectorAll('span').forEach((x,i)=>x.textContent=i<fRating?'★':'☆');}
function addFood(){const n=document.getElementById('food-name'),l=document.getElementById('food-list'),st=document.getElementById('food-style').value;if(!n||!n.value.trim())return;fReviews.push({name:n.value.trim(),rating:fRating,style:st,date:new Date().toISOString()});n.value='';fRating=0;updateFS();renderFood();}
function renderFood(){const l=document.getElementById('food-list');if(!l)return;const cls={gothic:'gothic-card',fanzine:'fanzine-card'};l.innerHTML=fReviews.map(r=>'<div class="'+cls[r.style]+'"><div style="display:flex;justify-content:space-between;"><b>'+r.name+'</b><span style="color:var(--pink);">'+'★'.repeat(r.rating)+'☆'.repeat(5-r.rating)+'</span></div><div style="font-size:8px;color:var(--txt2);">'+new Date(r.date).toLocaleDateString()+'</div></div>').join('')||'<div style="text-align:center;color:var(--txt2);padding:30px;">No reviews...</div>';}
let blogPosts=[];
function postBlog(){const t=document.getElementById('bp-title'),b=document.getElementById('bp-text'),f=document.getElementById('bp-font');if(!b||!b.value.trim())return;blogPosts.unshift({title:t?.value||'Untitled',text:b.value.trim(),font:f?.value||'comic',date:new Date().toISOString()});t.value='';b.value='';renderBlog();toast('Posted!');}
function renderBlog(){const l=document.getElementById('blog-list');if(!l)return;const ff={comic:'Comic Sans MS,cursive',pixel:'VT323,monospace',cyber:'Orbitron,sans-serif',cute:'Comic Sans MS,cursive'};l.innerHTML=blogPosts.map(e=>'<div class="paint-window"><div class="paint-bar">'+e.title+'<div class="pb-close">x</div></div><div class="paint-body"><div style="font-size:9px;color:#999;">'+new Date(e.date).toLocaleDateString()+'</div><div style="font-family:'+(ff[e.font]||'cursive')+';font-size:14px;color:#333;line-height:1.5;margin-top:6px;">'+e.text+'</div></div></div>').join('')||'<div style="text-align:center;color:var(--txt2);padding:30px;">No posts...</div>';}
let pins=[];
function pinNote(){const t=document.getElementById('pin-text');if(!t||!t.value.trim())return;pins.push({text:t.value.trim(),x:10+Math.random()*75+'%',y:10+Math.random()*65+'%',r:((Math.floor(Math.random()*5))-2)*4});t.value='';renderPins();}
function renderPins(){const el=document.getElementById('pinboard');if(!el)return;el.innerHTML=pins.map(p=>'<div style="position:absolute;left:'+p.x+';top:'+p.y+';transform:rotate('+p.r+'deg);" class="floating-note"><button class="nx" onclick="this.parentElement.remove();pins=pins.filter(x=>x.text!==\''+p.text.replace(/'/g,"\\'")+'\')">x</button>'+p.text+'</div>').join('')||'<div style="text-align:center;color:#8B6914;padding:60px;">Pin notes...</div>';}
let calD=new Date(),evts=[];
function initCalendar(){renderCal();}
function renderCal(){const y=calD.getFullYear(),m=calD.getMonth();document.getElementById('cal-month').textContent=new Date(y,m).toLocaleString('default',{month:'long',year:'numeric'}).toUpperCase();const g=document.getElementById('cal-grid');if(!g)return;const dn=['SUN','MON','TUE','WED','THU','FRI','SAT'];g.innerHTML=dn.map(d=>'<div style="font-size:7px;text-align:center;color:var(--pink2);background:rgba(255,20,147,.08);padding:4px;font-family:Silkscreen;">'+d+'</div>').join('');const fd=new Date(y,m,1).getDay(),ld=new Date(y,m+1,0).getDate();for(let i=0;i<fd;i++)g.innerHTML+='<div style="aspect-ratio:1;background:rgba(255,255,255,.02);"></div>';const today=new Date().toDateString();for(let d=1;d<=ld;d++){const ds=new Date(y,m,d).toDateString();g.innerHTML+='<div style="aspect-ratio:1;background:'+(ds===today?'var(--pink)':'rgba(255,255,255,.03)')+';display:flex;align-items:center;justify-content:center;font-size:11px;flex-direction:column;'+(ds===today?'color:#fff;font-weight:bold;':'')+'">'+d+(evts.some(e=>e.date===ds)?'<span style="font-size:6px;color:var(--lime);">●</span>':'')+'</div>';}}
function addEvent(){const t=document.getElementById('evt-name'),d=document.getElementById('evt-date');if(!t||!d||!t.value.trim()||!d.value)return;evts.push({title:t.value.trim(),date:new Date(d.value+'T00:00:00').toDateString()});t.value='';d.value='';renderCal();toast('Event added!');}
let corkPhotos=JSON.parse(localStorage.getItem('wf_corkPhotos')||'[]');
function initAlbum(){renderCork();}
function deletePhoto(idx){corkPhotos.splice(idx,1);saveCork();renderCork();updateDeskItems();}function renderCork(){const el=document.getElementById('cork-album');if(!el)return;el.innerHTML=corkPhotos.map((p,i)=>'<div style="position:relative;display:inline-block;margin:4px;transform:rotate('+((i%5)-2)*3+'deg);max-width:110px;cursor:pointer;" onclick="addPhotoCaption('+i+')"><img src="'+p.src+'" style="width:100%;display:block;border:3px solid #fff;box-shadow:2px 3px 6px rgba(0,0,0,.3);"><div onclick="event.stopPropagation();deletePhoto('+i+')" style="position:absolute;top:-6px;right:-6px;background:red;color:#fff;width:18px;height:18px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:10px;cursor:pointer;z-index:5;">X</div>'+(p.caption?'<div style="position:absolute;top:-8px;left:-8px;background:#fff9a8;padding:3px 8px;font-family:Comic Sans MS,cursive;font-size:9px;color:#333;box-shadow:2px 2px 4px rgba(0,0,0,.2);transform:rotate(3deg);max-width:90px;">'+p.caption+'</div>':'<div style="position:absolute;top:4px;left:4px;background:rgba(0,0,0,.5);color:#fff;font-size:8px;padding:2px 5px;border-radius:3px;font-family:Silkscreen;">post-it</div>')+'</div>').join('')||'<div style="text-align:center;color:#8B6914;padding:60px;">Upload photos, then click them to add notes...</div>';}

function saveCork(){localStorage.setItem('wf_corkPhotos',JSON.stringify(corkPhotos));}function uploadCork(e){const files=e.target.files;if(!files.length)return;Array.from(files).forEach(f=>{const r=new FileReader();r.onload=ev=>{corkPhotos.push({src:ev.target.result,caption:'',date:new Date().toLocaleDateString()});renderCork();updateDeskItems();};r.readAsDataURL(f);});toast(files.length+' photo(s) added! Click photo to add note.');}
function addPhotoCaption(idx){
  const cap=prompt('Add a note to this photo:')||'';
  corkPhotos[idx].caption=cap;renderCork();updateDeskItems();
}
let tama={hunger:50,happiness:50,energy:50,stage:1,born:Date.now()};
function initTama(){const s=localStorage.getItem('wf12_tama');if(s)tama=JSON.parse(s);if(!tama.born)tama.born=Date.now();updateTamaUI();setInterval(tamaDecay,40000);}
function tamaDecay(){tama.hunger=Math.max(0,tama.hunger-2);tama.happiness=Math.max(0,tama.happiness-1);tama.energy=Math.max(0,tama.energy-1);updateTamaUI();saveTama2();}
function tamaAction(a){if(a==='feed')tama.hunger=Math.min(100,tama.hunger+15);if(a==='play')tama.happiness=Math.min(100,tama.happiness+15);if(a==='clean')tama.energy=Math.min(100,tama.energy+10);if(a==='heal'){tama.hunger=Math.min(100,tama.hunger+8);tama.energy=Math.min(100,tama.energy+12);}if(tama.hunger===100&&tama.happiness===100&&tama.energy===100&&tama.stage<3){tama.stage++;toast('Tamagotchi grew!');}updateTamaUI();saveTama2();}
function updateTamaUI(){document.getElementById('thb').style.width=tama.hunger+'%';document.getElementById('thv').textContent=tama.hunger;document.getElementById('thpb').style.width=tama.happiness+'%';document.getElementById('thpv').textContent=tama.happiness;document.getElementById('teb').style.width=tama.energy+'%';document.getElementById('tev').textContent=tama.energy;const ss=['🥚','🐣','🐤','🐔'];const disp=document.getElementById('tama-disp');if(disp){disp.textContent=ss[tama.stage]||'🥚';disp.className='tama-creature'+(tama.stage>=3?' adult':tama.stage>=2?' teen':' baby');}document.getElementById('tama-name').textContent='TAMA v'+tama.stage;document.getElementById('tama-age').textContent=Math.floor((Date.now()-(tama.born||Date.now()))/86400000)||0;document.getElementById('tama-wt').textContent=5+tama.stage*5;}
function saveTama2(){if(!tama.born)tama.born=Date.now();localStorage.setItem('wf12_tama',JSON.stringify(tama));}
function initWinamp(){}
function waPlay(){const t=document.getElementById('wa-track');const cd=document.querySelector('.bb-cd');const btn=document.getElementById('bb-play');if(t.textContent.includes('PLAYING')){t.textContent='♫ PAUSED ♫';cd?.classList.add('paused');if(btn)btn.textContent='▶';}else{t.textContent='♫ PLAYING ♫';cd?.classList.remove('paused');if(btn)btn.textContent='⏸';}}
function waPrev(){document.getElementById('wa-track').textContent='♫ PREV ♫';}
function waNext(){document.getElementById('wa-track').textContent='♫ NEXT ♫';}
function embedSpotify(){let u=document.getElementById('spotify-url').value.trim();if(u.includes('?'))u=u.split('?')[0];const m=u.match(/spotify\.com\/(track|album|playlist)\/([a-zA-Z0-9]{22})/);if(!m){toast('Invalid URL: '+u.substring(0,40));return;}localStorage.setItem('wf_sp',u);const el=document.getElementById('spotify-embed');el.style.height='80px';el.style.overflow='hidden';el.style.cursor='pointer';el.onclick=function(){window.open(u,'_blank');};el.innerHTML='<iframe src="https://open.spotify.com/embed/'+m[1]+'/'+m[2]+'" width="100%" height="80" frameborder="0" allow="encrypted-media" style="border-radius:4px;"></iframe>';document.getElementById('wa-track').textContent='SPOTIFY LOADED';document.querySelector('.bb-cd')?.classList.remove('paused');const btn=document.querySelector('.bb-play');if(btn)btn.textContent='⏸';const sm=document.getElementById('sb-music');if(sm)sm.textContent='Spotify';toast('Loaded! (Click if blocked)');}function sendChat(){const i=document.getElementById('chat-input');if(!i||!i.value.trim())return;addChatMsg((localStorage.getItem('wf_username')||C?.email?.split('@')[0]||'you')||'you',i.value.trim());i.value='';const fp=document.getElementById('fp-msg');if(fp)fp.innerHTML='1 NEW<br>MSG';}
function addChatMsg(u,m){const c=document.getElementById('chat-msgs');if(!c)return;if(c.querySelector('div[style]'))c.innerHTML='';c.innerHTML+='<div style="margin-bottom:2px;color:#333;"><b style="color:var(--pink);">'+u+':</b> '+m+'</div>';c.scrollTop=c.scrollHeight;}
let gToken=null;
function generateGuestLink(){const t=crypto.randomUUID();gToken=t;const b=document.getElementById('guest-link-box');b.classList.remove('hidden');b.innerHTML='<div style="word-break:break-all;font-size:8px;">#guest/'+t+'</div><div style="font-family:Orbitron;font-size:14px;color:var(--lime);" id="g-timer">05:00</div><button class="btn w95" onclick="navigator.clipboard.writeText(\'#guest/'+t+'\');toast(\'Copied!\')">copy</button>';let s=300;const int=setInterval(()=>{s--;const m=Math.floor(s/60),sec=s%60;document.getElementById('g-timer').textContent=String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0');if(s<=0){clearInterval(int);b.innerHTML='<span style="color:red;">EXPIRED</span>';}},1000);}
window.addEventListener('beforeunload',()=>{if(gToken)navigator.sendBeacon(SB_URL+'/rest/v1/guest_tokens?token=eq.'+gToken,JSON.stringify({destroyed:true}));});
let peer=null,call=null,ls=null;
function initPeer(){try{peer=new Peer('wf12-'+Date.now().toString(36),{config:{iceServers:[{urls:'stun:stun.l.google.com:19302'}]}});peer.on('open',id=>{document.getElementById('my-peer-id').textContent=id;});peer.on('call',async c=>{if(confirm('Incoming call! Accept?')){const s=await getMedia();c.answer(s);handleCall(c);}else{c.close();}});}catch(e){}}
async function getMedia(){try{ls=await navigator.mediaDevices.getUserMedia({video:true,audio:true});return ls;}catch(e){toast('Camera denied');return null;}}
async function startCall(){const tid=document.getElementById('peer-id-input').value.trim();if(!tid||!peer)return;const s=await getMedia();if(!s)return;call=peer.call(tid,s);handleCall(call);openPopup('popup-tv');}
function handleCall(c){call=c;c.on('stream',rs=>{document.getElementById('remote-video').srcObject=rs;document.getElementById('local-video').style.display='block';document.getElementById('local-video').srcObject=ls;});c.on('close',()=>{document.getElementById('remote-video').srcObject=null;stopMedia();});}
function stopMedia(){if(ls){ls.getTracks().forEach(t=>t.stop());ls=null;}}
async function startScreenShare(){if(!call)return;try{const ss=await navigator.mediaDevices.getDisplayMedia({video:true});const sender=call.peerConnection.getSenders().find(s=>s.track?.kind==='video');if(sender)sender.replaceTrack(ss.getVideoTracks()[0]);ss.getVideoTracks()[0].onended=()=>{if(ls)sender.replaceTrack(ls.getVideoTracks()[0]);};}catch(e){}}
function sendStreamChat(){const i=document.getElementById('stream-chat-input');if(!i||!i.value.trim())return;const c=document.getElementById('stream-chat');c.innerHTML+='<div style="font-size:8px;"><b>'+((localStorage.getItem('wf_username')||C?.email?.split('@')[0]||'you')||'you')+':</b> '+i.value.trim()+'</div>';c.scrollTop=c.scrollHeight;i.value='';}
const EMOJIS=['💖','🌟','🦋','🌸','✨','💎','🎀','⭐','🦩','🪻','🍬','💕','🕊️','🌺','🎵','🍄','🌈','💫','🧸','🍭','💀','🖤','🎸','🪩','👾','🌙','🍒','💜','🕸️','🔥'];
function emojiDrop(){for(let i=0;i<6;i++){setTimeout(()=>{const e=document.createElement('div');e.className='emoji-burst';e.textContent=EMOJIS[Math.floor(Math.random()*EMOJIS.length)];e.style.left=(3+Math.random()*85)+'%';e.style.top=(5+Math.random()*70)+'%';document.getElementById('app-main').appendChild(e);setTimeout(()=>e.remove(),2600);},i*180);}toast('Emoji drop!');}
function spawnPostIt(){const cl=['#fff9a8','#ffb6c1','#e0ffff','#ccff00'];const el=document.createElement('div');el.className='floating-note';el.style.background=cl[Math.floor(Math.random()*cl.length)];el.style.left=(5+Math.random()*70)+'%';el.style.top=(5+Math.random()*65)+'%';const txt=prompt('Post-it text:');if(!txt)return;el.innerHTML='<button class="nx" onclick="this.parentElement.remove()">x</button>'+txt;el.addEventListener('mousedown',noteDrag);document.getElementById('app-main').appendChild(el);}
function noteDrag(e){const el=e.target.closest('.floating-note');if(!el)return;const ox=e.clientX-el.offsetLeft,oy=e.clientY-el.offsetTop;function mv(ev){el.style.left=(ev.clientX-ox)+'px';el.style.top=(ev.clientY-oy)+'px';}function up(){document.removeEventListener('mousemove',mv);document.removeEventListener('mouseup',up);}document.addEventListener('mousemove',mv);document.addEventListener('mouseup',up);}
function toggleSidebar(){document.body.classList.toggle('sb-hidden');const t=document.querySelector('.sb-toggle');if(t)t.textContent=document.body.classList.contains('sb-hidden')?'▶':'◀';const hidden=document.body.classList.contains('sb-hidden');const anchor=document.getElementById('ipod-anchor');if(anchor)anchor.style.left=hidden?'50%':'calc((100vw + 185px)/2)';updateDeskItems();}
function playYT(){const u=document.getElementById('yt-url').value.trim();const btn=document.getElementById('ipod-play');if(btn&&btn.textContent==='Pause'){document.getElementById('ipod-screen').innerHTML='<div style="color:#0f0;text-align:center;font-family:Silkscreen;font-size:10px;">PASTE YOUTUBE URL</div>';btn.textContent='Play';document.getElementById('sb-music').textContent='No track';return;}const m=u.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/);if(!m){toast('Invalid URL');return;}localStorage.setItem('wf_yt',u);document.getElementById('ipod-screen').innerHTML='<iframe src="https://www.youtube.com/embed/'+m[1]+'" allowfullscreen style="width:100%;height:100%;border:none;background:#000;"></iframe>';document.getElementById('sb-music').textContent='YT PLAYING';document.querySelector('.bb-cd')?.classList.remove('paused');const bb=document.getElementById('bb-play');if(bb)bb.textContent='Pause';if(btn)btn.textContent='Pause';toast('Playing!');}function playPrev(){toast('prev');}
function playPrev(){toast('prev');}
function playNext(){toast('next');}
const MSGS=[['hey bestie!!','omg did u see the new layout??','yessss its so y2k i love it'],['wyd rn?','customizing my avatar for the 50th time...','mood tbh'],['my tamagotchi has a better sleep schedule than me','LMAOOO same','we should feed it'],['remember that embarrassing thing from 2007?','PLS DONT REMIND ME','too late']];
function rotateBubbles(){const msgs=MSGS[Math.floor(Math.random()*MSGS.length)];const el=document.getElementById('iphone-msgs');if(!el)return;el.innerHTML='';msgs.forEach((m,i)=>{setTimeout(()=>{const d=document.createElement('div');d.className='imsg'+(i%2===0?' reply':'');d.textContent=m;el.appendChild(d);},i*800);});}
setInterval(rotateBubbles,20000);setTimeout(rotateBubbles,600);
const FILM_GIFS=[{src:'https://i.pinimg.com/originals/87/e2/e0/87e2e02f70cd4ed3f14d707fc1eb516b.gif',cap:'mood'},{src:'https://i.pinimg.com/originals/c1/b7/90/c1b79059622fb0c0cda30a7895ac4fb8.gif',cap:'vibes'},{src:'https://i.pinimg.com/originals/03/b7/7b/03b77be9013ae731c17809cfb743e36e.gif',cap:'slay'},{src:'https://i.pinimg.com/originals/46/f1/ac/46f1ac827de4f7a9e5521a864321bb0b.gif',cap:'y2k'},{src:'https://i.pinimg.com/originals/84/9b/0d/849b0d3f428a3e726db7d6ce97d76afb.gif',cap:'girl'},{src:'https://i.pinimg.com/originals/54/65/7f/54657fdf199b1c3f7a2e8f355e20496b.gif',cap:'star'},{src:'https://i.pinimg.com/originals/68/e3/0c/68e30c98e0c864a77c16a278a49bb230.gif',cap:'love'},{src:'https://i.pinimg.com/originals/56/53/96/5653966e4a9209b6719819194f27c4eb.gif',cap:'cyber'},{src:'https://i.pinimg.com/originals/8f/dc/8b/8fdc8b8a2be09d3ffae54e608c9b42e7.gif',cap:'tech'},{src:'https://file.garden/Zztv0a9yEhr5pmEq/play.png',cap:'play'}];
function initFilmstrip(){const track=document.getElementById('filmstrip-track');if(!track)return;const items=[...FILM_GIFS,...FILM_GIFS];track.innerHTML=items.map((g,i)=>'<div class="film-polaroid" style="--r:'+((i%3)-1)*3+'deg"><img src="'+g.src+'"><div class="fp-cap">'+g.cap+'</div></div>').join('');}
setTimeout(initFilmstrip,200);
setTimeout(()=>{const v=['gba','gbb','gbc','gbd'];document.querySelectorAll('.game-btn').forEach(b=>{b.classList.remove('gba','gbb','gbc','gbd');b.classList.add(v[Math.floor(Math.random()*v.length)]);});const sb=document.getElementById('btn-sky');if(sb)sb.textContent=document.body.classList.contains('sky')?'🌙 DARK':'☀️ LIGHT';},100);
function updateDeskItems(){
  const pp=localStorage.getItem('wf_profile_photo');const EU=[{name:C?(localStorage.getItem('wf_username')||(localStorage.getItem('wf_username')||C?.email?.split('@')[0]||'you')||'you'):'angel_bby',img:pp||'https://i.pinimg.com/originals/68/e3/0c/68e30c98e0c864a77c16a278a49bb230.gif',title:'untitled - Paint'},{name:C?(localStorage.getItem('wf_username')||(localStorage.getItem('wf_username')||C?.email?.split('@')[0]||'you')||'you'):'angel_bby',img:C?'data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%2250%22 height=%2250%22><rect fill=%22%23ff1493%22 width=%2250%22 height=%2250%22/><text fill=%22white%22 x=%2225%22 y=%2232%22 text-anchor=%22middle%22 font-size=%2220%22>'+C.email[0].toUpperCase()+'</text></svg>':'https://i.pinimg.com/originals/68/e3/0c/68e30c98e0c864a77c16a278a49bb230.gif',title:'untitled - Paint'},{name:'angel_bby',img:'https://i.pinimg.com/originals/68/e3/0c/68e30c98e0c864a77c16a278a49bb230.gif',title:'untitled - Paint'},{name:'cyber_kittn',img:'https://i.pinimg.com/originals/87/e2/e0/87e2e02f70cd4ed3f14d707fc1eb516b.gif',title:'my_art.bmp'},{name:'vampy_gurl',img:'https://i.pinimg.com/originals/46/f1/ac/46f1ac827de4f7a9e5521a864321bb0b.gif',title:'avatar.gif'},{name:'pix3l_prince',img:'https://i.pinimg.com/originals/84/9b/0d/849b0d3f428a3e726db7d6ce97d76afb.gif',title:'selfie.jpg'},{name:'st4r_boy',img:'https://i.pinimg.com/originals/03/b7/7b/03b77be9013ae731c17809cfb743e36e.gif',title:'mypic.png'},{name:'gl1tter_g0th',img:'https://i.pinimg.com/originals/54/65/7f/54657fdf199b1c3f7a2e8f355e20496b.gif',title:'photo.bmp'}];
  const home=document.getElementById('view-home');
  if(!home||!home.classList.contains('active')){document.querySelectorAll('.desk-card').forEach(c=>c.remove());return;}
  document.querySelectorAll('.desk-card').forEach(c=>c.remove());
  const sw=document.body.classList.contains('sb-hidden')?0:185;
  const vw=window.innerWidth,vh=window.innerHeight;
  const icx=vw/2+(sw>0?92:0),iw=320,iy=vh-370;
  const L={x1:sw+120,x2:icx-iw/2-100,y1:250,y2:iy-60};
  const R={x1:icx+iw/2+30,x2:vw-130,y1:250,y2:iy-60};
  const placed=[];
  function ov(x,y,w,h){return placed.some(p=>Math.abs(x-p.x)<(w+p.w)/2+15&&Math.abs(y-p.y)<(h+p.h)/2+15);}
  EU.forEach((u,i)=>{
    const card=document.createElement('div');card.className='user-card desk-card';card.style.position='fixed';card.style.pointerEvents='all';
    let x,y;
    if(i===0){x=sw+3;y=135;}else if(i===1){x=sw+3;y=245;}else if(i===2){x=sw+3;y=355;}
    else{const zone=i%2===0?L:R;let tries=0;do{x=zone.x1+Math.random()*Math.max(0,zone.x2-zone.x1);y=zone.y1+Math.random()*Math.max(0,zone.y2-zone.y1);tries++;}while(ov(x,y,95,105)&&tries<30);}
    placed.push({x,y,w:95,h:105});
    card.style.left=x+'px';card.style.top=y+'px';card.style.zIndex='55';
    card.innerHTML='<div class="uc-status"></div><img src="'+u.img+'" style="width:50px;height:50px;object-fit:cover;border-radius:50%;border:2px solid var(--pink);display:block;margin:0 auto;background:linear-gradient(135deg,var(--pink),var(--cyan));"><div class="uc-name">@'+u.name+'</div><div class="uc-title">'+u.title+'</div>';
    card.addEventListener('mousedown',userCardDrag);document.body.appendChild(card);
  });
  corkPhotos.slice(-6).forEach((p,i)=>{
    const d=document.createElement('div');d.className='desk-polaroid desk-card';d.style.position='fixed';d.style.pointerEvents='all';
    const maxX=icx-iw/2-110;const x=Math.min(sw+120+(i*100)%400,maxX);const y=260+(i*60)%(iy-340);
    d.style.left=x+'px';d.style.top=y+'px';d.style.zIndex='50';d.style.setProperty('--r',((i%5)-2)*3+'deg');
    d.innerHTML='<img class="dp-img" src="'+p.src+'"><div class="dp-cap">'+(p.caption||p.date||'recent')+'</div>';
    d.addEventListener('mousedown',deskPolaroidDrag);d.addEventListener('dblclick',()=>navigateTo('view-album'));document.body.appendChild(d);
  });
}
function userCardDrag(e){const card=e.target.closest('.user-card');if(!card)return;card.style.zIndex=75;const ox=e.clientX-card.offsetLeft,oy=e.clientY-card.offsetTop;function mv(ev){card.style.left=(ev.clientX-ox)+'px';card.style.top=(ev.clientY-oy)+'px';}function up(){card.style.zIndex=55;document.removeEventListener('mousemove',mv);document.removeEventListener('mouseup',up);}document.addEventListener('mousemove',mv);document.addEventListener('mouseup',up);}
function deskPolaroidDrag(e){const el=e.target.closest('.desk-polaroid');if(!el)return;el.style.zIndex=70;el._dragged=false;const ox=e.clientX-el.offsetLeft,oy=e.clientY-el.offsetTop;function mv(ev){el.style.left=(ev.clientX-ox)+'px';el.style.top=(ev.clientY-oy)+'px';el._dragged=true;}function up(){el.style.zIndex=50;document.removeEventListener('mousemove',mv);document.removeEventListener('mouseup',up);}document.addEventListener('mousemove',mv);document.addEventListener('mouseup',up);}
setTimeout(()=>{updateDeskItems();const un=localStorage.getItem('wf_username');if(un)document.getElementById('av-username').value=un;},800);
// Restore saved YouTube & Spotify on load
setTimeout(()=>{
  const yt=localStorage.getItem('wf_yt');if(yt){document.getElementById('yt-url').value=yt;playYT();}
  const sp=localStorage.getItem('wf_sp');if(sp){document.getElementById('spotify-url').value=sp;embedSpotify();}
},1000);


